name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          # registry-url: https://npm.pkg.github.com
          # scope: "@Fndroid"
      - run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.PKG_GITHUB_TOKEN}}
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PKG_GITHUB_TOKEN}}
